### PR TITLE
Add theme field to User

### PR DESCRIPTION
**Pull request by astagi**

### CODE REVIEW

**Comment by bameda** [comment]
Thanks, :dancer: :dancer:

**Comment by astagi** [comment]
Yw :smile: 
I forgot to mention that it's related to the custom themes PR opened in taiga-front. https://github.com/taigaio/taiga-front/pull/489

**Comment by bameda** [comment]
I know, I know....

**Comment by astagi** [comment]
Ah ok :smile: :smile:

**Pull request merged**
