### PR TITLE
Add filter by email domain on register

### PR DESCRIPTION
**Pull request by jespino**

### CODE REVIEW

**Comment by bameda** [comment]
No test

**Comment by jespino** [comment]
Now have tests!

**Comment by superalex** [comment]
I've been thinking about this one and in my opinion we should also control the user email update and limit it to the valid domains too. If we add this one I would rename REGISTER_ALLOWED_DOMAINS to USER_EMAIL_ALLOWED_DOMAINS.

@bameda @jespino what do you think about it?

**Comment by bameda** [comment]
It makes sense. User must use always a valid domain too in:
- register form
- editing their profiles 
- **sending invitations**

**Pull request merged**
