### PR TITLE
Solving issue #1961 Assign Multiple Users to the Task

### PR DESCRIPTION
**Pull request by gracebar**
There  were many requests from the users corresponding to the above mentioned request. We felt it's more suitable to have this feature.

### CODE REVIEW

**Comment by bameda** [comment]
Hi @gracebar 

this PR is incomplete, this is a good start but:

- what about endpoints in the API?
- what about the history of changes?
- what about the timelines?
- what happens with the notification emails?
- what happens with the webhooks?
- what happens with csv repots?
- what about the importer/exporter?
- test

.. and what about taiga-front?

**Comment by gracebar** [comment]
Hello David,

So do you mean that the current changes related to the tasks is correct and
has to be enhanced on the other objects like csv reports, timelines etc. I
verified the migration on the backend under localhost:8001/admin/ and it
works but I did not do the updates in the taiga-front. I developed this
part to prove the functionality metrics suitability in my software
evolution course and I wish to continue to enhance the logic to other
dependent objects when time permits. I might need your assistance in doing
so.

Best regards,
Grace

**Comment by bameda** [comment]
The change is correct :-} but insufficient to be merged becuase the issue has not solved, the functionality is incomplete.

You can work on it and we assist you (of course).

**Comment by bameda** [comment]
Hi @gracebar, we have been doing some housecleaning work prior to Taiga6 upcoming release and we are rejecting old PRs that we didn't correctly attend back them. Currently multiple assignment works on User Stories and we want to evaluate implementing it for other entities in the short term after Taiga6 will be released. We encourage you to wait some time and propose a new PR if we don't develop your enhancement. This time we will make sure to review it when it comes through. Thank you very much on behalf of the Taiga Team!

**Pull request closed without merging**
