### PR TITLE
Search also into tags fields

### LINKED ISSUE #276: Search for a tag does not find the tagged US
I added a tag "node-info" to a US, now I search for node-info and does not get any result...

I would expect that tags are searched to.

### PR DESCRIPTION
**Pull request by volans-**
Changed the search queries to search also into the tags fields.
Fixes #276

### CODE REVIEW

**Comment by volans-** [comment]
Tested on Taiga 1.10.0, PostgreSQL 9.4.5-0+deb8u1

**Comment by bameda** [comment]
This needs performance tests with  a big DB.

**Comment by bameda** [comment]
But we can make something like we do in `taiga.projects.filters.QFilterBackend` te get a rank because subject is more important than tags and tags are more important than description.

**Comment by superalex** [comment]
I've tested with a big DB and the performance is ok.

I'm missing including it too in the issues and backlog sections

**Comment by jespino** [comment]
Moved to the PR #784 and included some extra cnahges :smiley:

**Pull request closed without merging**
