### PR TITLE
Issue#2943: Regenerate refs for tasks, issues and user stories on project change

### PR DESCRIPTION
**Pull request by jespino**

### CODE REVIEW

**Comment by superalex** [comment]
It's not working properly for issues or tasks. I miss tests for those.

**Comment by jespino** [comment]
Ok, I review this. Thanks :smile:

**Comment by jespino** [comment]
I think now is ready (waiting for the tests). Added some extra functionality like try to detect the status, priority, severity, type of the objects, and remove milestone and user_story, because doesn't be the same in other project.

Need a good review, anyway the code must affect only to the updates where the project_id change.

**Comment by superalex** [comment]
I've been playing with curl and works great! :)

**Pull request merged**
