### PR TITLE
i18n

### PR DESCRIPTION
**Pull request by bameda**
image

### CODE REVIEW

**Comment by superalex** [comment]
Is it ready to merge?

I think requirements.txt should be updated:

>python scripts/manage_translations.py fetch
>/bin/sh: tx: command not found

**Comment by bameda** [comment]
No, it's not ready to merge.

trasifex-client works with python 2.x so

```
pip2 install --user transifex-client
```

**Comment by superalex** [comment]
If it need an extra package it should be documented somewhere...could it be useful that the --help parameters also talks about it?

**Comment by bameda** [comment]
It's at the beginning of the script

```
##################################################################
####         INSTRUCTIONS BEFORE TO USE THIS SCRIPTS:         ####
##################################################################
#
# 1. Install transifex-client (it works with
#    python 2.x)
#
#       $ pip2.7 install --user transifex-client
#
# 2. Create ~/.transifexrc file:
#
#       $ vim ~/.transifexrc
#
#       [https://www.transifex.com]
#       hostname = https://www.transifex.com
#       username = <YOUR_USERNAME>
#       password = <YOUR_PASSWOR>
```

**Comment by bameda** [comment]
Ok, now if you do not have tx yet:

```
(taiga)bameda@cosmiclatte ~/k/p/2/t/taiga-back> python scripts/manage_translations.py lang_stats

You need transifex-client, install it.

 1. Install transifex-client, use

       $ pip install --upgrade -r requirements-devel.txt

    or

       $ pip install --upgrade transifex-client==0.11.1b0

 2. Create ~/.transifexrc file:

       $ vim ~/.transifexrc"

       [https://www.transifex.com]
       hostname = https://www.transifex.com
       username = <YOUR_USERNAME>
       password = <YOUR_PASSWOR>
                  
(taiga)bameda@cosmiclatte ~/k/p/2/t/taiga-back>
```

**Comment by superalex** [comment]
Great! :+1:

**Pull request merged**
