### PR TITLE
Uploading file with multiple extensions

### PR DESCRIPTION
**Pull request by al42and**
When uploading file with multiple dots in its name, like `archive.tar.gz`, only last extension is preserved, and the rest of the filename is passed to `django.template.defaultfilters.slugify` function which removes any dots. As a result, file is saved as `archivetar.gz`.

[Relevant code](https://github.com/taigaio/taiga-back/blob//9d94de9b219c2783673a18d517b36b33a222174c/taiga/projects/attachments/models.py#L35).

Better solution seems to be `django.utils.text.get_valid_filename` function, specifically designed for filtering filenames. This also allows for unicode filenames.
The proposed patch was tested with `stable` and `master` branches of Taiga, installed with taiga-scripts and using Django 1.7.8.

BTW, filename is converted to lowercase, which seems unnecessary to me, but whatever.

### CODE REVIEW

**Comment by jespino** [comment]
I like it! :+1:

**Comment by jespino** [comment]
I will remove the .lower() too.

**Comment by jespino** [comment]
Merged manually through cherry-pick. Thanks! :sparkles:

**Comment by jespino** [comment]
And removed the .lower() in master too. Thanks again! :smiley:

**Comment by al42and** [comment]
You also need to remove `.lower()` in [api.py](https://github.com/taigaio/taiga-back/blob/master/taiga/projects/attachments/api.py#L59), otherwise the name in file list in the bottom of wiki page is still lowercase.

**Comment by jespino** [comment]
You are completely right, and in other 2 places (export_import/service.py and sample_data.py). Thanks one more time!

**Comment by jespino** [comment]
Done! :smiley:

**Comment by al42and** [comment]
You're welcome. I'm glad that I was able to help.

**Pull request closed without merging**
