### PR TITLE
Improve github hooks messages

### PR DESCRIPTION
**Pull request by bameda**
image

### CODE REVIEW

**Comment by Xaviju** [comment]
I love it! :heart:  but until we don't have a link to the user profile, I will not show the link to the user profile

**Comment by bameda** [comment]
No, the link go to github users profile, GitHub (in green) is the Taiga user

**Comment by Xaviju** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by superalex** [comment]
I think I found a problem with the message i18n:

taiga

**Comment by bameda** [comment]
This bugs was fixed in master of taiga-front 8 days ago

https://github.com/taigaio/taiga-front/commit/c6d24ba4ffee489fb08e466d76e74ce49fdea1ff

:dancer:  :dancer: :dancer: :dancer: :dancer: :dancer:

**Comment by superalex** [comment]
In slack the message is shown with escaped chars:

taiga

**Comment by bameda** [comment]
Yep, this is a long, long bug in slack pluging. You can see a lot of errors with the comment field at the #taiga-notifications channel

**Comment by superalex** [comment]
Ok!

**Pull request merged**
