### PR TITLE
usage of  cached_property

### PR DESCRIPTION
**Pull request by gam-phon**

### CODE REVIEW

**Comment by superalex** [comment]
Thank you very much @gam-phon, 

I think that if using a cached_property here we should rename get_cached_user_stories to cached_user_stories in the milestone model too, this way it will be more consistent. 

@bameda have you got any comments about this?

**Comment by bameda** [comment]
I agree

**Comment by gam-phon** [comment]
Welcome @superalex

**Comment by superalex** [comment]
Merged here: https://github.com/taigaio/taiga-back/pull/650

Thank you very much @gam-phon :+1:

**Comment by gam-phon** [comment]
Welcome ^_^

**Pull request closed without merging**
