### PR TITLE
Translate and fix all emails

### PR DESCRIPTION
**Pull request by bameda**
TODO: 
 - [x] Improve invitation email.
 - [x] Fix text in import/export emails

### CODE REVIEW

**Comment by superalex** [comment]
Tests keep failing...

**Comment by bameda** [comment]
I'll fix today

**Comment by bameda** [comment]
Fixed

**Comment by superalex** [comment]
Still failing...

**Comment by superalex** [comment]
@jespino ...

**Comment by jespino** [comment]
It's fail because @bameda change the body of the export/import response, we have to update the tests :smiley:

**Pull request merged**
