### PR TITLE
Us/1233/expose import export

### PR DESCRIPTION
**Pull request by jespino**

### CODE REVIEW

**Comment by superalex** [comment]
I think it would be better if when exporting a project the response mimetype would allow you directly to download a file

**Comment by jespino** [comment]
completely agree

**Comment by jespino** [comment]
Fixed!

**Comment by superalex** [comment]
- Email isn't sent when load_dump is executed via celery
 - It would be great adding throttling to project export to avoid DOS

**Comment by jespino** [comment]
Included both changes!

**Comment by superalex** [comment]
Cool, works great!,

I think the importer should generate the project slug instead reading it from the file :)

**Comment by superalex** [comment]
Cool! :+1:

**Pull request merged**
