### PR TITLE
Improvement on cors prevention

### PR DESCRIPTION
**Pull request by zhaoyuxuan**

### CODE REVIEW

**Comment by zhaoyuxuan** [comment]
Change Access-Control-Max-Age from 3600 to 1800 will help prevent unsafe cors prelonged caching, which can result in unauthorized cross domain access to sensitive resources

**Comment by zhaoyuxuan** [comment]
Removing "Put" "Delete" as they are considered as cors unsafe methods, which could allow attacker to inject malicious code or delete resources.

**Comment by zhaoyuxuan** [comment]
removed Patch as it is also considered as preflighted request

**Comment by bameda** [comment]
Merged in taiga6 ( #1531 )

Thanks @zhaoyuxuan for your contribution.

**Pull request closed without merging**
