### PR TITLE
Adding Jira, Trello, Asana, PivotalTracker and Github importers to back

### PR DESCRIPTION
**Pull request by jespino**

### CODE REVIEW

**Comment by Kyslik** [comment]
I can not install asana api any clues?

Not even pip install asana works (workon taiga).

**Comment by jespino** [comment]
Asana client comes from the asana people (https://github.com/Asana/python-asana/). But I can uninstall and install it again correctly in my machine. Looks like an environment problem. Can you pass the ~/.pip/pip.log information?

**Comment by Kyslik** [comment]
I have an ansible suite set up to install Taiga, (worked on previous release).

Anyway: I updated pip and setuptools 
```
pip install --upgrade setuptools pip
```

And `pip install...` went ok with one error (regarding asana) but continued and finished.

```
Downloading/unpacking asana==0.6.2 (from -r requirements.txt (line 42))
  Downloading asana-0.6.2.tar.gz
  Running setup.py (path:/tmp/pip-build-jestajk9/asana/setup.py) egg_info for package asana
  Invalid requirement: 'requests~=2.9.1' (('Expected version spec in', 'requests~=2.9.1', 'at', '~=2.9.1')) in requirement asana==0.6.2 (from -r requirements.txt (line 42))
  Invalid requirement: 'requests_oauthlib~=0.6.1' (('Expected version spec in', 'requests_oauthlib~=0.6.1', 'at', '~=0.6.1')) in requirement asana==0.6.2 (from -r requirements.txt (line 42))
  Invalid requirement: 'six~=1.10.0' (('Expected version spec in', 'six~=1.10.0', 'at', '~=1.10.0')) in requirement asana==0.6.2 (from -r requirements.txt (line 42))
Downloading/unpacking sampledata (from django-sampledatahelper==0.4.1->-r requirements.txt (line 4))
  Downloading sampledata-0.3.7.tar.gz (178kB): 178kB downloaded
  Running setup.py (path:/tmp/pip-build-jestajk9/sampledata/setup.py) egg_info for package sampledata
```

---

I am 100% you need to update installing guide. Perhaps dependency list is "out of date" I am not sure...

```
    - build-essential
    - binutils-doc
    - autoconf
    - flex
    - bison
    - libjpeg-dev
    - libfreetype6-dev
    - zlib1g-dev
    - libzmq3-dev
    - libgdbm-dev
    - libncurses5-dev
    - automake
    - libtool
    - libffi-dev
    - tmux
    - gettext
    - python3
    - python3-pip
    - python-dev
    - python3-dev
    - python-pip
    - virtualenvwrapper
    - libxml2-dev
    - libxslt-dev
```


I am going to experiment on VMs and report back.

**Comment by Kyslik** [comment]
I am suspecting following: I am using Debian 8, so python3-pip may be not latest.

**Comment by jespino** [comment]
Yes, maybe, the installation process is oriented to ubuntu, and more exactly for ubuntu 16.04.

**Comment by Kyslik** [comment]
Alright updating setuptools / pip works, thanks for quick reposnse.

Sorry to bother you further, any clue about this? templates and users worked nice

```
(.venv)taiga@matrix:~/taiga-back$ python manage.py loaddata initial_role
Trying import local.py settings...
CommandError: No fixture named 'initial_role' found.
```

**Comment by bameda** [comment]
@Kyslik try only with with 

```
python manage.py loaddata initial_project_templates
```

 `initial_role` has no sense.

**Comment by Kyslik** [comment]
In your manuals you mention initial_role thats why I was trying to seed it.

Yes Taiga works with only project_templates thanks :)

**Pull request merged**
