### PR TITLE
US#1913: CSV Reports

### PR DESCRIPTION
**Pull request by jespino**

### CODE REVIEW

**Comment by bameda** [comment]
All users can show uuids via API

**Comment by superalex** [comment]
I don't fully understand the change and now the tests are failing...

**Comment by bameda** [comment]
Don't worry, Jesus and I are at the wheel :smiley_cat:

**Comment by superalex** [comment]
Okidoki! :+1:

**Comment by bameda** [comment]
Custom attributes not appear in the csv file

**Comment by bameda** [comment]
Custom attributes not appear in the csv file

**Pull request merged**
