### PR TITLE
Refactors over taiga.projects.api

### PR DESCRIPTION
**Pull request by bameda**
Refactors over taiga.projects.api: 
 - use taiga.base instead rest_framework, 
 - move some mixins to taiga.projects.mixins.

Fix a typo in taiga.projects.permissions.

### CODE REVIEW

**Comment by superalex** [comment]
Cool! :+1:

**Comment by alex-oleshkevich** [comment]
Just curious, what was the reason to drop DRF and reimplement it locally?

**Comment by morenoh149** [comment]
@alex-oleshkevich same question here. I found this project looking for a midsized example drf project. But you removed it.

**Comment by alex-oleshkevich** [comment]
@morenoh149 looks like there was a licensing issue. But better to wait for their answer.

**Pull request merged**
