### PR TITLE
Fix userstories filter data counters

### PR DESCRIPTION
**Pull request by bameda**
For you @superalex with love

### CODE REVIEW

**Comment by superalex** [comment]
Ups!, sorry, I missed that join with projects table.

Just one comment, "LEFT JOIN" and "LEFT OUTER JOIN" do the same, did you change it to make the code more consistent or there are more reasons?

**Comment by bameda** [comment]
Is the sale.  The chance is o la forma consistente.

**Comment by superalex** [comment]
Have you been drinking? :cocktail:

**Comment by bameda** [comment]
Fucking autocorrector. The change is for code consistence. 

(but nevertheless I am drinking right now)

 ;-p

**Comment by superalex** [comment]
image

**Comment by bameda** [comment]
Yes, it's me

**Comment by superalex** [comment]
Great! :)

**Pull request merged**
