### PR TITLE
Fix errors in bitbuket hook calls

### PR DESCRIPTION
**Pull request by bameda**
See https://tree.taiga.io/project/taiga/issue/3299

### CODE REVIEW

**Comment by superalex** [comment]
Great!, thank you very much @bameda :+1:

**Comment by bameda** [comment]
We can backport this to stable and upgrade taiga.io

**Comment by superalex** [comment]
Sure!, are you backporting it?

**Comment by bameda** [comment]
Yep

**Comment by bameda** [comment]
Done

**Comment by superalex** [comment]
Great! ;)

**Pull request merged**
