### PR TITLE
dependencies required by manage.py

### PR DESCRIPTION
**Pull request by rharriso**
dev instruction wouldn't run until I added these to the requirements.
Might be needed on master

### CODE REVIEW

**Comment by bameda** [comment]
Hi @rharriso, this PR isn't necessary because celery installs these requirements itself (https://github.com/celery/celery/blob/master/requirements/default.txt). I just tested it:

```
bameda@stewie ~> mkvirtualenv -p /usr/bin/python3 test-celery-setup       
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in test-celery-setup/bin/python3
Also creating executable in test-celery-setup/bin/python
Installing setuptools, pip...done.
(test-celery-setup)bameda@stewie ~> pip install celery==3.1.17
Downloading/unpacking celery==3.1.17
  Downloading celery-3.1.17-py2.py3-none-any.whl (514kB): 514kB downloaded
Downloading/unpacking pytz>dev (from celery==3.1.17)
  Downloading pytz-2015.2-py2.py3-none-any.whl (476kB): 476kB downloaded
Downloading/unpacking kombu>=3.0.24,<3.1 (from celery==3.1.17)
  Downloading kombu-3.0.24-py2.py3-none-any.whl (238kB): 238kB downloaded
Downloading/unpacking billiard>=3.3.0.19,<3.4 (from celery==3.1.17)
  Downloading billiard-3.3.0.19.tar.gz (150kB): 150kB downloaded
  Running setup.py (path:/home/bameda/.virtualenvs/test-celery-setup/build/billiard/setup.py) egg_info for package billiard
    
    warning: no files found matching '*.py' under directory 'Lib'
Downloading/unpacking anyjson>=0.3.3 (from kombu>=3.0.24,<3.1->celery==3.1.17)
  Downloading anyjson-0.3.3.tar.gz
  Running setup.py (path:/home/bameda/.virtualenvs/test-celery-setup/build/anyjson/setup.py) egg_info for package anyjson
    
Downloading/unpacking amqp>=1.4.5,<2.0 (from kombu>=3.0.24,<3.1->celery==3.1.17)
  Downloading amqp-1.4.6.tar.gz (77kB): 77kB downloaded
  Running setup.py (path:/home/bameda/.virtualenvs/test-celery-setup/build/amqp/setup.py) egg_info for package amqp
    
Installing collected packages: celery, pytz, kombu, billiard, anyjson, amqp
  Running setup.py install for billiard
    
    warning: no files found matching '*.py' under directory 'Lib'
  Running setup.py install for anyjson
    Fixing build/lib/anyjson/__init__.py
    Skipping implicit fixer: buffer
    Skipping implicit fixer: idioms
    Skipping implicit fixer: set_literal
    Skipping implicit fixer: ws_comma
    Fixing build/lib/anyjson/__init__.py
    Skipping implicit fixer: buffer
    Skipping implicit fixer: idioms
    Skipping implicit fixer: set_literal
    Skipping implicit fixer: ws_comma
    
  Running setup.py install for amqp
    
Successfully installed celery pytz kombu billiard anyjson amqp
Cleaning up...
(test-celery-setup)bameda@stewie ~> 
```

Maybe an error occurred in the execution and these dependencies were not installed for this reason

Thank you very much for using and contributing to Taiga.

**Comment by rharriso** [comment]
Then the production install instructions need to be updated.

**Comment by bameda** [comment]
Why? Celery is in requirements.txt so you install it when run ```pip install -r requirements.txt```

**Comment by rharriso** [comment]
I just went through the instructions step by step, and had to adjust
requirements.txt

**Comment by superalex** [comment]
Hello @rharriso,

I think something failed when you installed the celery package, if you check the package requirements:
```
pip show celery
```

kombu and billiard are listed

```
---
Name: celery
Version: 3.1.17
Location: /home/superalex/Envs/taiga/lib/python3.4/site-packages
Requires: pytz, kombu, billiard
```

What's the hw of the machine where you were installing Taiga?

Regards,

**Comment by rharriso** [comment]
I'll need to reset the VM. I'll get back to you after I go through the install again.

**Comment by superalex** [comment]
Thanks!

**Pull request closed without merging**
