### PR TITLE
:sparkles: Add settings for new backlog options.

### PR DESCRIPTION
**Pull request by jwir3**
This adds two new settings for projects: default_backlog_order_scrum and
default_backlog_order_kanban. Each of these is used to control the users'
settings for whether new stories should be added to the top or bottom
(default) of the respective workflows.

This is in support of the following issue: https://tree.taiga.io/project/taiga/issue/4352

### CODE REVIEW

**Comment by jwir3** [comment]
NOTE: This was re-committed from https://github.com/taigaio/taiga-back/pull/1616

**Comment by yamila-moreno** [comment]
Hi @jwir3 thanks for your contribution!! ✨ 

we've reviewed the code and there are some changes that should be performed in order to be accepted, for example the addition of tests.

Nonetheless, I strongly recommend to not go ahead in this PR until you review the [front pr](https://github.com/kaleidos-ventures/taiga-front/pull/23) that has some changes that could impact the backend implementation.

**Comment by jwir3** [comment]
> we've reviewed the code and there are some changes that should be performed in order to be accepted, for example the addition of tests.

Sure, is it just the addition of tests, or are there other things that also need to be changed?

> Nonetheless, I strongly recommend to not go ahead in this PR until you review the front pr that has some changes that could impact the backend implementation.

Yes, I'm reviewing that now.

Thank you,

**Comment by yamila-moreno** [comment]
Hi @jwir3 this was already solved with only-front changes. Now you can choose whether to create the US on the top or on the bottom.

Cheers!

**Pull request closed without merging**
